name: toto-fran
base: core20
version: '0.1'
summary: Holaaaaaa
description: |
  This snap will be THE snap that will change everythingasdf
parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
